spring:
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          hazelcast.instance_name: hazelcastInstance
          region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
  datasource.driver-class-name: org.h2.Driver